#spring:
#  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.255.23.25:3306/demo-activiti?nullCatalogMeansCurrent=true
#    username: root
#    password: P@ssw0rd2020
#
#  activiti:
#    database-schema-update: create  # more: drop-create
#    # 开启历史库
#    db-history-used: true
#    history-level: audit

spring.main.allow-circular-references: true