POST http://localhost:8080/api/goods/v1/add
Content-Type: application/json

{
  "name": "小米手机",
  "price": 5999.00,
  "num": 1000
}

###

POST http://localhost:8080/api/user/v1/register
Content-Type: application/json

{
  "likes": ["乒乓球"],
  "password": "12345678",
  "username": "admin",
  "phone": "18111568078",
  "birthDate": "2020-05-08",
  "email": "123@123.com",
  "idCardNo": "123456789012345678"
}

###
