spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo-jpa
#    username: root
#    password: 123456

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: none
      ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
#    url: jdbc:mysql://127.0.0.1:3306/e_commerce?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/demo-jpa
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: DemoJpaHikariCP