spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo_mybatis

mybatis:
  type-aliases-package: com.fengwenyi.springboot.mybatis.entity
  mapper-locations: classpath:mapper/*.xml