#spring:
#  application:
#    name: mybatis-plus-code-generator
#  thymeleaf:
#    enabled: true
#    prefix: classpath:/templates/
#    mode: HTML
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    suffix: .html
#    cache: false
#  mvc:
#    static-path-pattern: /static/**